/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mlib_ops */

#ifndef _Included_mlib_ops
#define _Included_mlib_ops
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mlib_ops
 * Method:    madd
 * Signature: (Lmlib/matrixbp;Lmlib/matrixbp;Lmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_mlib_ops_madd
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     mlib_ops
 * Method:    msub
 * Signature: (Lmlib/matrixbp;Lmlib/matrixbp;Lmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_mlib_ops_msub
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     mlib_ops
 * Method:    mscale
 * Signature: (Lmlib/matrixbp;FLmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_mlib_ops_mscale
  (JNIEnv *, jclass, jobject, jfloat, jobject);

/*
 * Class:     mlib_ops
 * Method:    mmul
 * Signature: (Lmlib/matrixbp;Lmlib/matrixbp;Lmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_mlib_ops_mmul
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     mlib_ops
 * Method:    mmul_byelem
 * Signature: (Lmlib/matrixbp;Lmlib/matrixbp;Lmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_mlib_ops_mmul_1byelem
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     mlib_ops
 * Method:    mtpose
 * Signature: (Lmlib/matrixbp;Lmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_mlib_ops_mtpose
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
