from typing import List, Tuple, Union, Optional
from mbp16dpy import matrixbp

class actp:
    ReLU = 0
    ReLU6 = 1
    LeakyReLU = 2
    Sigmoid = 3
    Sigmoid_hard = 4
    Tanh = 5
    Tanh_hard = 6
    Sign = 7
    Pass = 8

class netdef:
    pass

class mlptrain:
    def __init__(self, netsrc: netdef, *, totalgrad_cap: Union[bool, int] = False) -> None: ...
    def execute(self, vecin: matrixbp, vecout: Optional[matrixbp] = None) -> matrixbp: ...
    def backward(self, grad: matrixbp, lr: float) -> None: ...
    def finalgrads(self, vecgrad0: Optional[matrixbp] = None) -> matrixbp: ...
    def isgradsaver(self) -> bool: ...

class mlpexec:
    def __init__(self, netsrc: netdef) -> None: ...
    def execute(self, vecin: matrixbp, vecout: Optional[matrixbp] = None) -> matrixbp: ...
    def __call__(self, vecin: matrixbp, vecout: Optional[matrixbp] = None) -> matrixbp: ...

def buildnet(netdef_list: List[Tuple[int, int, int, float]]) -> netdef: ...
def savemodel(modelsrc: netdef, filename: str, *, filetype: str = "bin", exposemrk: str = "") -> None: ...
def loadmodel(filepath: str) -> netdef: ...
def savegrads(model_or_totalgrads: mlptrain, dest_totalgrads_cap: mlptrain) -> None: ...