from typing import List, Union

class matrixbp:
    def __init__(self, rows: int, cols: int) -> None: ...
    def __repr__(self) -> str: ...
    def fromlist(self, lstin: List[Union[int, float]]) -> None: ...
    def fromrand(self) -> None: ...
    def tolist(self, *, arr2d: Union[bool, int] = 0) -> Union[List[float], List[List[float]]]: ...

def madd(m1: matrixbp, m2: matrixbp, mr: matrixbp) -> None: ...
def msub(m1: matrixbp, m2: matrixbp, mr: matrixbp) -> None: ...
def mscale(m1: matrixbp, scale: Union[int, float], mr: matrixbp) -> None: ...
def mmulElem(m1: matrixbp, m2: matrixbp, mr: matrixbp) -> None: ...
def mmul(m1: matrixbp, m2: matrixbp, mr: matrixbp) -> None: ...
def mtpose(m1: matrixbp, mr: matrixbp) -> None: ...