from typing import Tuple
from mbp16dpy import matrixbp

def averpool(graphin: matrixbp, poolsize: Tuple[int, int], step: int, graphout: matrixbp) -> None: ...
def maxpool(graphin: matrixbp, poolsize: Tuple[int, int], step: int, graphout: matrixbp, idx_of_maxs: matrixbp) -> None: ...
def averpool_backward(graphin: matrixbp, poolsize: Tuple[int, int], step: int, graphout: matrixbp) -> None: ...
def maxpool_backward(graphin: matrixbp, idx_of_maxs: matrixbp, poolsize: Tuple[int, int], step: int, graphout: matrixbp) -> None: ...
def padding(graphin: matrixbp, r_extend: int, c_extend: int, graphout: matrixbp) -> None: ...
def cutedges(graphin: matrixbp, r_sub: int, c_sub: int, graphout: matrixbp) -> None: ...