#include "filedump.h"
#include <stdio.h>
#include <string.h>

int savemodel(const char *fname ,uint32_t lyrcnt ,const netLyrConf *modelsrc){
    FILE *dest = fopen(fname,"wb");
    int ret = 0;
    if(!dest) return lmlp_FILENOTEXIST;

    if(fwrite(lmlpBINMARK, sizeof(char), 15, dest) < 0){
        ret = lmlp_DUMPBINHEADER_ERR;
        goto _file_clerup;
    }
    if(fwrite(&lyrcnt, sizeof(uint32_t), 1, dest) < 0){
        ret = lmlp_DUMPBINHEADER_ERR;
        goto _file_clerup;
    }

    lmlp_model_binlyrheaderdef dumptmp;

    for(uint32_t i = 0; i < lyrcnt; i++){
        netLyrConf *curlyr = &modelsrc[i];
        uint16_t indim = curlyr->in_dim, outdim = curlyr->out_dim;
        dumptmp.acTp = curlyr->acTp;
        dumptmp.dExa = curlyr->dExtra;
        dumptmp.in_dim = indim;
        dumptmp.out_dim = outdim;
        if(fwrite(&dumptmp, sizeof(lmlp_model_binlyrheaderdef), 1, dest) < 0){
            ret = lmlp_DUMPINFOD_ERR;
            goto _file_clerup;
        }
        if(fwrite(curlyr->weights, sizeof(qfix), indim * outdim, dest) < 0){
            ret = lmlp_DUMPINFOW_ERR;
            goto _file_clerup;
        }
        if(fwrite(curlyr->bias, sizeof(qfix), outdim, dest) < 0){
            ret = lmlp_DUMPINFOB_ERR;
            goto _file_clerup;
        }

    }

_file_clerup:
    fclose(dest);
    return ret;
}

int loadmodel(const char *fname, netLyrConf *dstnet){
    FILE *filesrc = fopen(fname, "rb");
    if(!filesrc) return lmlp_FILENOTEXIST;
    int ret = 0;
    char fheaderstr[16];
    if(fread(fheaderstr, sizeof(char), 15, filesrc) < 0){
        ret = lmlp_LOADFILEINFO_ERR;
        goto _err_ret;
    }
    if(strncmp(fheaderstr, lmlpBINMARK, 15) != 0){
        ret = lmlp_FILEVERIFY_FAIL;
        goto _err_ret;
    }
    uint32_t lyrcnt;
    if(fread(&lyrcnt, sizeof(uint32_t), 1, filesrc) < 0){
        ret = lmlp_LOADFILEINFO_ERR;
        goto _err_ret;
    }

    dstnet = (netLyrConf*)malloc(sizeof(netLyrConf) * lyrcnt);
    lmlp_model_binlyrheaderdef curcap;
    for (uint32_t i = 0; i < lyrcnt; i++){
        if(fread(&curcap, sizeof(lmlp_model_binlyrheaderdef), 1, filesrc) < 0){
            ret = lmlp_LOADINFOD_ERR;
            goto _err_ret;
        }
        netLyrConf *curlyr = &dstnet[i];
        uint16_t indim = curcap.in_dim;
        uint16_t outdim = curcap.out_dim;
        curlyr->acTp = curcap.acTp;
        curlyr->dExtra = curcap.dExa;
        curlyr->in_dim = indim;
        curlyr->out_dim = outdim;
        curlyr->weights = (qfix*)malloc(sizeof(qfix) * indim * outdim);
        curlyr->bias = (qfix*)malloc(sizeof(qfix) * outdim);
        if(fread(curlyr->weights, sizeof(qfix), indim * outdim, filesrc) < 0){
            ret = lmlp_LOADINFOW_ERR;
            goto _err_ret;
        }
        if(fread(curlyr->bias, sizeof(qfix), outdim, filesrc) < 0){
            ret = lmlp_LOADINFOB_ERR;
            goto _err_ret;
        }
    }
    fclose(filesrc);
    return lyrcnt;
_err_ret:
    fclose(filesrc);
    return ret;
}

int dump_asCHeader(const char *fname, const char *modelname ,uint32_t lyrcnt ,const netLyrConf *modelsrc){
    int ret = 0;
    FILE *hExport = fopen(fname, "w");
    if(!hExport) return lmlp_FILENOTEXIST;
    fprintf(hExport, "//auto-generated by lightMLP\n//DO NOT edit it immeditly\n");
    fprintf(hExport, "#ifndef _lmlpmod_%s_\n#define _lmlpmod_%s_\n", modelname, modelname);
    for(uint32_t i = 0; i < lyrcnt; i++){
        netLyrConf *curlyr = &modelsrc[i];
        uint16_t indim = curlyr->in_dim;
        uint16_t outdim = curlyr->out_dim;
        uint32_t w_size = indim * outdim;
        qfix *wwritesrc = curlyr->weights;
        qfix *bwritesrc = curlyr->bias;
        fprintf(hExport, "const int32_t %s_weights_%d[] = { 0x%X", modelname, i, wwritesrc[0]);
        for(uint32_t j = 1; j < w_size; j++) fprintf(hExport, ", 0x%X", wwritesrc[j]);
        fprintf(hExport, " };\nconst int32_t %s_bias_%d[] = { 0x%X", modelname, i, bwritesrc[0]);
        for(uint16_t j = 1; j < outdim; j++) fprintf(hExport, ", 0x%X", bwritesrc[j]);
        fprintf(hExport, " };\n\n");    
    }
    
    fprintf(hExport, "const netLyrConf %s[] = {\n", modelname);
    
    for(uint32_t i = 0; i < lyrcnt; i++){
        netLyrConf *curlyr = &modelsrc[i];
        fprintf(hExport, "\t{%d, %d, %d, %s_weights_%d, %s_bias_%d, 0x%X}\n",curlyr->acTp, curlyr->in_dim, curlyr->out_dim, modelname, i, modelname, i, curlyr->dExa);
    }
    fprintf(hExport, "};\n\n#endif");
    fclose(hExport);
    return ret;
}
