/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mlib_matrixbp */

#ifndef _Included_mlib_matrixbp
#define _Included_mlib_matrixbp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mlib_matrixbp
 * Method:    setupmbp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mlib_matrixbp_setupmbp
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mlib_matrixbp
 * Method:    printmatrix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mlib_matrixbp_printmatrix
  (JNIEnv *, jobject);

/*
 * Class:     mlib_matrixbp
 * Method:    fromlist
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_mlib_matrixbp_fromlist
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     mlib_matrixbp
 * Method:    fromrand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mlib_matrixbp_fromrand
  (JNIEnv *, jobject);

/*
 * Class:     mlib_matrixbp
 * Method:    toarr_new
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_mlib_matrixbp_toarr_1new
  (JNIEnv *, jobject);

/*
 * Class:     mlib_matrixbp
 * Method:    toarr_cpy
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_mlib_matrixbp_toarr_1cpy
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     mlib_matrixbp
 * Method:    rows
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mlib_matrixbp_rows
  (JNIEnv *, jobject);

/*
 * Class:     mlib_matrixbp
 * Method:    cols
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mlib_matrixbp_cols
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
