/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_mlpexec */

#ifndef _Included_core_mlpexec
#define _Included_core_mlpexec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_mlpexec
 * Method:    setupexec
 * Signature: (Lcore/netdef;)V
 */
JNIEXPORT void JNICALL Java_core_mlpexec_setupexec
  (JNIEnv *, jobject, jobject);

/*
 * Class:     core_mlpexec
 * Method:    execute
 * Signature: (Lmlib/matrixbp;Lmlib/matrixbp;)V
 */
JNIEXPORT void JNICALL Java_core_mlpexec_execute
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     core_mlpexec
 * Method:    deallocexec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_core_mlpexec_deallocexec
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
