/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_netdef */

#ifndef _Included_core_netdef
#define _Included_core_netdef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_netdef
 * Method:    setup_ndef
 * Signature: ([Lcore/netlyr;)V
 */
JNIEXPORT void JNICALL Java_core_netdef_setup_1ndef
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     core_netdef
 * Method:    setup_fromfile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_core_netdef_setup_1fromfile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     core_netdef
 * Method:    freemodel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_core_netdef_freemodel
  (JNIEnv *, jobject);

/*
 * Class:     core_netdef
 * Method:    savemodel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_core_netdef_savemodel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
